config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :vehicles
  # resources :vehicles, only: %i[index new create show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :brand, :model, :year, :kind, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #render html: '<h2>Olá mundo</h2>'.html_safe
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all.order(created_at: :asc)
  end

  def new # New é do front
    @vehicle = Vehicle.new
  end

  def create # Create é do back
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new # Chama o new da instância atual sem perder os dados já digitados.
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end
  
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
      redirect_to vehicle_path(@vehicle)
    else
      render :edit # Chama o new da instância atual sem perder os dados já digitados.
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to vehicle_path
  end

  private 

  def vehicle_params
    params.require(:vehicle).permit(:brand, :model, :year, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Olá mundo</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/edit.html.erb
<h2>Edit Vehicle</h2>
<% if @vehicle.errors.any? %>
  <% @vehicle.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
  <% end %>
<% end %>

<%= form_with model: @vehicle, data: {turbo: false} do |form| %>
  <p>
    <%= form.label :brand, 'Brand:' %>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :model, 'Model:' %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year, 'Year:' %>
    <%= form.number_field :year %>
  </p>
  <p>
    <%= form.label :kind, 'Kind:' %>
    <%= form.number_field :kind %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/vehicles/index.html.erb
<h2>Vehicles</h2>
<p>
  <%= link_to 'New Vehicle', new_vehicle_path %>
</p>

<% @vehicles.each do |vehicle| %>
  <p>
    <%= vehicle.id %> |
    <%= vehicle.brand %> |
    <%= vehicle.model %> |
    <%= vehicle.year %> |
    <%= vehicle.kind %> |
    <%= link_to 'Details', vehicle_path(vehicle) %>
    <%= link_to 'Edit', edit_vehicle_path(vehicle) %>
    <%= link_to 'Erase', vehicle_path(vehicle), data: {'turbo-method': :delete, 'turbo-confirm': 'Deseja mesmo deletar esse veículo ?'} %>
  </p>
<% end %>

app/views/vehicles/new.html.erb
<h2>New Vehicle</h2>
<% if @vehicle.errors.any? %>
  <% @vehicle.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
  <% end %>
<% end %>

<%= form_with model: @vehicle, data: {turbo: false} do |form| %>
  <p>
    <%= form.label :brand, 'Brand:' %>
    <%= form.text_field :brand %>
  </p>
  <p>
    <%= form.label :model, 'Model:' %>
    <%= form.text_field :model %>
  </p>
  <p>
    <%= form.label :year, 'Year:' %>
    <%= form.number_field :year %>
  </p>
  <p>
    <%= form.label :kind, 'Kind:' %>
    <%= form.number_field :kind %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/vehicles/show.html.erb
<h2>Vehicle - id: <%= @vehicle.id %></h2>

<p>
  <%= @vehicle.brand %>
  <%= @vehicle.model %>
  <%= @vehicle.year %>
  <%= @vehicle.kind %>
</p>